name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: pip install -r code-appli-python/vote/requirements.txt
      - run: zip -r code-appli-python/app.zip code-appli-python
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: code-appli-python/app.zip

#  publish:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      -