name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name : Lint du code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: installation de librairies python
        run: pip install -r code-appli-python/vote/requirements.txt
      - name: zip du code
        run: zip -r code-appli-python/app.zip code-appli-python
      - name: upload d'artéfacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: code-appli-python/app.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: numéro de version
        id: get_version
        run: |
          num=$(curl --silent "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | jq length)
          echo "::set-output name=release_number::$(($num+1))"
      - name: création de la release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.release_number }}
          release_name: Release ${{ steps.get_version.outputs.release_number }}
          draft: false
          prerelease: false
      - name: upload d'artéfacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: code-appli-python/app.zip
          asset_name: app.zip
          asset_content_type: application/zip