name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name : Lint du code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: installation de librairies python
        run: pip install -r code-appli-python/vote/requirements.txt
      - name: zip du code
        run: zip -r code-appli-python/app.zip code-appli-python
      - name: upload d'artéfacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: code-appli-python/app.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Nom de la branche
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})"
      - name: création de la release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.BRANCH_NAME }}
          release_name: Release ${{ env.BRANCH_NAME }}
          draft: false
          prerelease: false